#!/bin/sh

export PATH="$HOME/scripts:$PATH"
export QT_STYLE_OVERRIDE='gtk2'

################
#    CONFIG    #
################
bspc config border_width 0
bspc config window_gap 12
bspc config focus_follows_pointer false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config click_to_focus true

# COLOR
bspc config focused_border_color    "#00A2FF"
bspc config presel_feedback_color   "#00A2FF"

# RULES
bspc rule -a Firefox locked=on
bspc rule -a Pavucontrol state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a Simplescreenrecorder state=floating
bspc rule -a gnuplot_qt state=floating
bspc rule -a Gnuplot state=floating
bspc rule -a Gpick state=floating
bspc rule -a Emacs state=tiled

# DESKTOP
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc desktop 2 -l monocle
#################

xsetroot -cursor_name left_ptr           # set the default mouse cursor
feh --bg-scale ~/Personal/Wallpapers/mountains.png
sxhkd &
compton -b
xfsettingsd &
xfce4-power-manager
/usr/bin/start-pulseaudio-x11 &
export QT_STYLE_OVERRIDE=GTK+            # use GTK theme for Qt-Apps
xhost +local:                            # allow local containers to access X
xset r rate 200 30                       # key auto-repeat   # key auto-repeat
xfce4-panel -d &
